config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get 'login' => 'sessions#new'
  get 'logout' => 'session#destroy'
  get 'signup' => 'users#new'

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users
  resources :subjects, only: [ :index ] do
    resources :grades, only: [ :index ]
  end
  resources :subject_lines, only: [ :index ] do
    collection do
    get :marks
    put :update_marks
    end
  end

end

app/models/grade.rb
class Grade < ActiveRecord::Base

  has_many :subjects
  has_many :users

end

app/models/mark.rb
class Mark < ActiveRecord::Base

  def self.update_values marks
    marks.each do |mark|
      where(subject_line_id: mark[:subject_line_id]).first.update_attributes value: mark[:value]
    end
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base

  validates :title, presence: true

  has_many :subject_lines
  belongs_to :teacher, class_name: 'User', foreign_key: :user_id
  belongs_to :grade

end

app/models/subject_line.rb
class SubjectLine < ActiveRecord::Base

  has_many :marks
  belongs_to :user
  belongs_to :subject

end

app/models/user.rb
class User < ActiveRecord::Base

  include Authentication

  attr_accessor :password

  email_regex = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  validates :fio, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: email_regex }
  validates :password, presence: true,
                       confirmation: true
  validates :password_confirmation, presence: true

  has_many :subject_lines
  has_many :subjects
  belongs_to :grade

  scope :students, -> { where(is_teacher: false) }
  scope :teachers, -> { where(is_teacher: true) }

  
  before_save :hash_password

  
  def self.authenticate email, password
    user = where(email: email).first
    if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end


  private

  def hash_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

end

app/models/user/authentication.rb
class User
  module Authentication

    def self.included klass
      klass.extend ClassMethods
      klass.before_save :hash_password
    end

    module ClassMethods
      def authenticate email, password
        user = where(email: email).first
        if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
          user
        else
          nil
        end
      end
    end


    private

    def hash_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.hashed_password = BCrypt::Engine.hash_secret(@password, salt)
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :login_required

  helper_method :current_user


  private

  def login_required
    redirect_to login_path, alert: 'Войдите в Контекст или создайте новый!' unless current_user
  end

  def teacher_required
    redirect_to login_path, alert: 'Эта страничка не предназначена для вас, увы' unless current_user.is_teacher?
  end

  def current_user
    @current_user ||= User.find session[:user_id] if session[:user_id]
  end

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  before_action :teacher_required, only: :index
  before_action :find_grades, only: :index

  def index
  end


  private

  def find_grades
    grade_ids = current_user.subjects.where(title: params[:subject_id]).pluck :grade_id
    @grades = Grade.find grade_ids
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required, only: [ :new, :create ]
  before_action :show_dashboard, only: :new

  def new
  end

  def create
    user = User.authenticate params[:email], params[:password]
    if user
      session[:user_id] = user.id
      redirect_to dashboard, notice: 'Добро пожаловать в Emark!'
    else
      flash.now.alert = 'Неверный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Выход из Emark успешно выполнен!'
  end


  private

  def show_dashboard
    redirect_to dashboard, notice: 'Добро пожаловать в Контекст!' if current_user
  end

  def dashboard
    if current_user.is_teacher?
      subjects_path
    else
      subject_lines_path
    end
  end

end

app/controllers/subject_lines_controller.rb
class SubjectLinesController < ApplicationController

  before_action :teacher_required, only: :marks
  before_action :find_grade, only: :marks
  before_action :find_subject, only: :marks

  def index
    @subject_lines ||= current_user.subject_lines
  end

  def marks
    @subject_lines ||= @grade.users.map{ |user| user.subject_lines.where(subject_id: @subject.id).first }
  end

  def update_marks
    Mark.update_values params[:marks]
    redirect_to :back, notice: 'Информация об оценках обновлена.'
  end


  private

  def find_grade
    @grade ||= Grade.find params[:grade_id]
  end

  def find_subject
    @subject ||= current_user.subjects.where(title: params[:subject_id], grade_id: params[:grade_id]).first
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  before_action :teacher_required, only: :index

  def index
    @subjects = current_user.subjects.pluck(:title).uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    permitted = params.require(:user).permit(:email, :fio, :password, :password_confirmation)
    @user = User.new permitted

    if @user.save
      redirect_to tasks_path, notice: 'Добро пожаловать в Emark!'
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/grades/_grade.html.erb
<li class="grades__grade">
  ➤ <%= link_to grade.title, marks_subject_lines_path(grade_id: grade.id, subject_id: params[:subject_id]) %>
</li>

app/views/grades/index.html.erb
<% content_for :menu_bar do %>
  <%= link_to 'Предметы', subjects_path %> > <%= params[:subject_id] %>
<% end %>

<ul class="grades">
  <%= render partial: 'grade', collection: @grades %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Emark</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <h1 class="app-title"><%= link_to 'Emark', root_path %></h1>

    <nav class="menu-bar">
      <%= yield :menu_bar %>
    </nav>

    <% flash.each do |type, content| %>
      <%= content_tag :div, content, class: "flash-content flash-content__#{type}" %>
    <% end %>

    <div class="screen">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subject_lines/_subject_line.html.erb
<li class="marks__subject-line">
  <span class="subject-line__student">
    <%= subject_line_counter + 1 %>. <%= subject_line.user.fio %>
  </span>

  <% subject_line.marks.each do |mark| %>
    <span class="subject-line__mark">
      <%= select_tag "marks[][value]", options_for_select((1..5).to_a, mark.value), include_blank: true %>
      <%= hidden_field_tag "marks[][subject_line_id]", subject_line.id %>
    </span>
  <% end %>
</li>

app/views/subject_lines/index.html.erb
<ul class="marks">
  <% @subject_lines.each do |subject_line| %>
    <li class="marks__subject-line">
      <span class="subject-line__subject">
        ➤ <%= subject_line.subject.title %>:
      </span>

      <% subject_line.marks.each do |mark| %>
        <span class="subject-line__mark">
          <%= mark.value %>
        </span>
      <% end %>
    </li>
  <% end %>
</ul>

<%= button_to "Отправить на почту", root_path %>

app/views/subject_lines/marks.html.erb
<% content_for :menu_bar do %>
  <%= link_to 'Предметы', subjects_path %> > <%= link_to params[:subject_id], subject_grades_path(params[:subject_id]) %> > <%= @grade.title %>
<% end %>

<%= form_tag :update_marks_subject_lines, method: :put do %>
  <ul class="marks">
    <%= render partial: 'subject_line', collection: @subject_lines %>
  </ul>

  <%= submit_tag 'Сохранить' %>
<% end %>

app/views/subjects/_subject.html.erb
<li class="subjects__subject">
  ➤ <%= link_to subject, subject_grades_path(subject) %>
</li>

app/views/subjects/index.html.erb
<% content_for :menu_bar do %>
  Предметы
<% end %>

<ul class="subjects">
  <%= render partial: 'subject', collection: @subjects %>
</ul>

app/views/users/new.html.erb
<section class="input-form">
  <h1>Новый Пользователь</h1>

  <%= form_for @user do |f| %>
    <div class="input-form__element">
      <%= f.label :email, 'Ваш email:' %><%= f.text_field :email %>
      <%#= error_on_field :email, f.object %>
    </div>

    <div class="input-form__element">
      <%= f.label :fio, 'Ваше ФИО:' %><%= f.text_field :fio %>
      <%#= error_on_field :fio, f.object %>
    </div>
    
    <div class="input-form__element">
      <%= f.label :password, 'Пароль:' %><%= f.password_field :password %>
      <%#= error_on_field :password, f.object %>
    </div>

    <div class="input-form__element">
      <%= f.label :password_confirmation, 'Пароль ещё раз:' %><%= f.password_field :password_confirmation %>
      <%#= error_on_field :password_confirmation, f.object %>
    </div>

    <%= submit_tag 'Создать Пользователя' %>
  <% end %>
</section>